#!/bin/bash

#working directory
working_dir=$(pwd)

#this function changes files to links for readme file in github
doing_job () {
	for file in *; do
		if [[ "$file" != "README.md" ]]; then
			echo "adding >>: - [$file](./$file)";
			echo "- [$file](./$file)" >> README.md
		fi
	done
}

#check if README.md exists
if [ -f "$./README.md" ]; then
	echo "Yeeey README.md exists in here now working starts...";
	doing_job
else
	echo "There is no README.md file here \"$working_dir\" try another folder";
	echo -n "do you want me to create one? y/n:> ";
	read CHOICE
	if [ "$CHOICE" = "y" ]; then
		echo "--> Let's create this README.md file";
		touch README.md;
		doing_job
	else
		echo "Okay sure no file for your"
	fi

fi
